name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  workflow_dispatch: # ← 手動実行用

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: rattize
          password: ${{ secrets.CR_PAT }}

      - name: Pull Docker image
        run: docker pull ghcr.io/rattize/my-latex-env:latest

      - name: Build PDF with LaTeX
        run: |
              docker run --rm -v ${{ github.workspace }}:/work -w /work \
              ghcr.io/rattize/my-latex-env:latest \
              latexmk -xelatex -shell-escape main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: main.pdf

